import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { ScopePaths } from "./scope.js";

export type IgnoreMode = "skills" | "all" | "none";

const BEGIN = "# agentlink:begin";
const END = "# agentlink:end";

export const IGNORE_MODES: IgnoreMode[] = ["skills", "all", "none"];

export function isIgnoreMode(value: string): value is IgnoreMode {
  return (IGNORE_MODES as string[]).includes(value);
}

/**
 * Which created links belong in .gitignore.
 *
 * Instructions aliases are one small file per harness and are the thing that
 * makes a fresh clone work for a teammate on a different harness, so they are
 * committed. Skill links are derived, multiply with every skill and harness,
 * and their parent directories also hold machine-local harness state, so they
 * are ignored and regenerated by `agentlink sync`.
 */
export function ignoreEntries(
  mode: IgnoreMode,
  input: { skillDirs: string[]; instructionFiles: string[] },
): string[] {
  const entries: string[] = [];
  if (mode === "none") return entries;
  for (const dir of input.skillDirs) entries.push(`${dir}/`);
  if (mode === "all") entries.push(...input.instructionFiles);
  return [...new Set(entries)].sort();
}

export interface IgnoreResult {
  changed: boolean;
  file: string;
  entries: string[];
  skipped?: string;
}

export function updateGitignore(
  paths: ScopePaths,
  mode: IgnoreMode,
  input: { skillDirs: string[]; instructionFiles: string[] },
  options: { dryRun?: boolean } = {},
): IgnoreResult {
  const file = path.join(paths.root, ".gitignore");
  const entries = ignoreEntries(mode, input);

  // Only touch a repository that actually tracks files here.
  if (paths.scope !== "project" || !existsSync(path.join(paths.root, ".git"))) {
    return { changed: false, file, entries, skipped: "not a git repository" };
  }

  const before = existsSync(file) ? readFileSync(file, "utf8") : "";
  const after = applyBlock(before, entries);
  const changed = after !== before;
  if (changed && !options.dryRun) writeFileSync(file, after, "utf8");
  return { changed, file, entries };
}

/** Remove the managed block, leaving the rest of .gitignore alone. */
export function removeIgnoreBlock(paths: ScopePaths, options: { dryRun?: boolean } = {}): boolean {
  const file = path.join(paths.root, ".gitignore");
  if (!existsSync(file)) return false;
  const before = readFileSync(file, "utf8");
  const after = applyBlock(before, []);
  if (after === before) return false;
  if (!options.dryRun) writeFileSync(file, after, "utf8");
  return true;
}

/** Read the entries currently inside the managed block. */
export function readIgnoreBlock(paths: ScopePaths): string[] {
  const file = path.join(paths.root, ".gitignore");
  if (!existsSync(file)) return [];
  const text = readFileSync(file, "utf8");
  const start = text.indexOf(BEGIN);
  if (start === -1) return [];
  const end = text.indexOf(END, start);
  if (end === -1) return [];
  return text
    .slice(start, end)
    .split("\n")
    .slice(1)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("#"));
}

function applyBlock(text: string, entries: string[]): string {
  const start = text.indexOf(BEGIN);
  const end = text.indexOf(END, start === -1 ? 0 : start);
  const withoutBlock =
    start === -1 || end === -1
      ? text
      : `${text.slice(0, start)}${text.slice(end + END.length)}`;

  // Normalise so repeated runs cannot accumulate blank lines either way.
  const cleaned = withoutBlock
    .replace(/\n{3,}/g, "\n\n")
    .replace(/^\n+/, "")
    .replace(/[ \t]*\n*$/, "");

  if (entries.length === 0) return cleaned === "" ? "" : `${cleaned}\n`;

  const block = [BEGIN, ...entries, END].join("\n");
  return cleaned === "" ? `${block}\n` : `${cleaned}\n\n${block}\n`;
}
