import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { writeFileAtomic } from "./link.js";
import type { ScopePaths } from "./scope.js";

export type IgnoreMode = "skills" | "all" | "none";

/** Matched as whole lines: a user comment like "# agentlink:beginning" is not our marker. */
const BEGIN_LINE = /^# agentlink:begin\s*$/m;
const END_LINE = /^# agentlink:end\s*$/m;
const BLOCK = "# agentlink:begin";

export const IGNORE_MODES: IgnoreMode[] = ["skills", "all", "none"];

export function isIgnoreMode(value: string): value is IgnoreMode {
  return (IGNORE_MODES as string[]).includes(value);
}

/**
 * Which created links belong in .gitignore.
 *
 * Instructions aliases are one small file per harness and are the thing that
 * makes a fresh clone work for a teammate on a different harness, so they are
 * committed. Skill links are derived, multiply with every skill and harness,
 * and their parent directories also hold machine-local harness state, so they
 * are ignored and regenerated by `agentlink sync`.
 */
export function ignoreEntries(
  mode: IgnoreMode,
  input: { skillDirs: string[]; instructionFiles: string[] },
): string[] {
  const entries: string[] = [];
  if (mode === "none") return entries;
  for (const dir of input.skillDirs) entries.push(`${dir}/`);
  if (mode === "all") entries.push(...input.instructionFiles);
  return [...new Set(entries)].sort();
}

export type BlockStatus = "updated" | "unchanged" | "malformed";

export interface IgnoreResult {
  status: BlockStatus;
  file: string;
  entries: string[];
  skipped?: string;
}

export function updateGitignore(
  paths: ScopePaths,
  mode: IgnoreMode,
  input: { skillDirs: string[]; instructionFiles: string[] },
  options: { dryRun?: boolean } = {},
): IgnoreResult {
  const file = path.join(paths.root, ".gitignore");
  const entries = ignoreEntries(mode, input);

  // Only touch a repository that actually tracks files here.
  if (paths.scope !== "project" || !existsSync(path.join(paths.root, ".git"))) {
    return { status: "unchanged", file, entries, skipped: "not a git repository" };
  }

  const before = existsSync(file) ? readFileSync(file, "utf8") : "";
  const spliced = applyIgnoreBlock(before, entries);
  if (spliced.status === "malformed") return { status: spliced.status, file, entries };

  const changed = spliced.status === "updated";
  if (changed && !options.dryRun) writeFileAtomic(file, spliced.text);
  return { status: spliced.status, file, entries };
}

/** Remove the managed block, leaving the rest of .gitignore alone. */
export function removeIgnoreBlock(paths: ScopePaths, options: { dryRun?: boolean } = {}): boolean {
  const file = path.join(paths.root, ".gitignore");
  if (!existsSync(file)) return false;
  const before = readFileSync(file, "utf8");
  const spliced = applyIgnoreBlock(before, []);
  if (spliced.status !== "updated" || spliced.text === before) return false;
  if (!options.dryRun) writeFileAtomic(file, spliced.text);
  return true;
}

/** Read the entries currently inside the managed block. */
export function readIgnoreBlock(paths: ScopePaths): string[] {
  const text = existsSync(path.join(paths.root, ".gitignore"))
    ? readFileSync(path.join(paths.root, ".gitignore"), "utf8")
    : "";
  return blockSpan(text)?.entries ?? [];
}

interface Span {
  start: number;
  end: number;
  entries: string[];
}

/** Locate the managed block by whole-line markers. Returns null when absent. */
function blockSpan(text: string): Span | null {
  const begin = BEGIN_LINE.exec(text);
  if (!begin) return null;
  const afterBegin = begin.index + begin[0].length;
  const end = END_LINE.exec(text.slice(afterBegin));
  if (!end) return null;
  const endIndex = afterBegin + end.index;
  const body = text.slice(afterBegin, endIndex);
  return {
    start: begin.index,
    end: endIndex + end[0].length,
    entries: body
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line.length > 0 && !line.startsWith("#")),
  };
}

export interface SpliceResult {
  text: string;
  status: BlockStatus;
}

/**
 * Insert, replace or remove the managed block.
 *
 * Text outside the block is never rewritten: no whitespace normalisation runs
 * over the user's file. A lone marker is refused rather than guessed at, since
 * anything after an unterminated block might be the user's own rules.
 */
export function applyIgnoreBlock(text: string, entries: string[]): SpliceResult {
  const beginMatch = BEGIN_LINE.exec(text);
  const endMatch = END_LINE.exec(text);
  if (beginMatch && !endMatch) {
    return { text, status: "malformed" };
  }
  if (!beginMatch && endMatch) {
    return { text, status: "malformed" };
  }

  const span = beginMatch && endMatch ? blockSpan(text) : null;
  const without = span ? `${text.slice(0, span.start)}${text.slice(span.end)}` : text;

  if (entries.length === 0) {
    if (!span) return { text, status: "unchanged" };
    // Remove the blank line the block was separated by, but nothing else.
    const trimmed = without.replace(/\n[ \t]*\n$/, "\n").replace(/\n$/, text.endsWith("\n") ? "\n" : "");
    return { text: trimmed, status: "updated" };
  }

  const block = [BLOCK, ...entries, "# agentlink:end"].join("\n");
  if (span) {
    const next = `${without.slice(0, span.start)}${block}\n${without.slice(span.start).replace(/^\n/, "")}`;
    return { text: next, status: next === text ? "unchanged" : "updated" };
  }

  const base = text.replace(/\s+$/, "");
  const next = base === "" ? `${block}\n` : `${base}\n\n${block}\n`;
  return { text: next, status: next === text ? "unchanged" : "updated" };
}
